
# Loads default set of integrations. Do not remove.
default_config:

# System Settings
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
simpleicons:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js

# Extra Sidebar Menu Options - IP's don't work ???
# panel_iframe:
#   router:
#     title: "Router"
#     url: "https://192.168.1.1
#     require_admin: true
#     icon: mdi:router-wireless-settings
#   nas:
#     title: "NAS"
#     url: "https://192.168.1.200"
#     require_admin: true
#     icon: mdi:nas

# Text to speech
tts:
  - platform: google_translate
    language: en
    tld: ca

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

# Device Tracker
#device_tracker:
  #- platform: bluetooth_tracker
   # host: 192.168.1.226
  #- platform: bluetooth_le_tracker

#Climate
climate:
## Fujitsu Heat Pumps
   - platform: fujitsu_general_heatpump
     username: !secret Fujitsu_U
     password: !secret Fujitsu_P
     region: 'us'
     tokenpath: 'token.txt'
   - platform: generic_thermostat
     name: Basement Bedroom
     heater: switch.basement_heater
     target_sensor: sensor.ewelink_th01_temperature

notify:
  - name: HAOS-Belnan
    platform: twitter
    consumer_key: !secret Twitter_APIKey
    consumer_secret: !secret Twitter_APISecret
    access_token: !secret Twitter_AccToken
    access_token_secret: !secret Twitter_AccSecret

#Device Tracker
device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin
    password: "!Balefir3"
    #password: "Timew8s4no1@"
    ssl: true

#Sensors
sensor:
## 17Track.net
  - platform: seventeentrack
    username: !secret Seventeen_U
    password: !secret Seventeen_P
## System Resources
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_use
      - type: disk_free
      - type: memory_use
      - type: memory_free
      - type: memory_use_percent
      - type: processor_temperature
      - type: processor_use
      #- type: ipv4_address
## Twitter
  - platform: rest
    name: School Closed
    resource: https://api.twitter.com/1.1/search/tweets.json
    value_template: '{{ value_json.statuses[0].text }}'
    scan_interval: 1800
    headers:
      Authorization: Bearer !secret Twitter_AccToken
    params:
      q: 'from:CCRCE_NS closed'
  - platform: rest
    name: School Paved
    resource: https://api.twitter.com/1.1/search/tweets.json
    value_template: '{{ value_json.statuses[0].text }}'
    scan_interval: 1800
    headers:
      Authorization: Bearer !secret Twitter_AccToken
    params:
      q: 'from:CCRCE_NS Paved'
  - platform: rest
    name: "ThaDuffman Test"
    resource: https://api.twitter.com/1.1/search/tweets.json
    value_template: '{{ value_json.statuses[0].text }}'
    scan_interval: 1800
    headers:
      Authorization: Bearer !secret Twitter_AccToken
    params:
      q: 'from:ThaDuffman Test'
  - platform: rest
    name: ccrce_ns_tweets
    resource: https://api.twitter.com/1.1/search/tweets.json?q=from%3Accrce_ns%20closed
    headers:
      Authorization: Bearer !secret Twitter_Bearer
    value_template: '{{ value_json.statuses[0].text }}'
    scan_interval: 1800

## Youtube Channel Tracker - https://github.com/custom-components/youtube
  - platform: youtube
    channel_id: !secret ItsFunneh_ID
    
#Binary Sensors

    
# Shell Commands
shell_command:
  github_auto_update: /bin/bash pushupdate.sh
  
  # making random change to config